/**
 * The morning briefing — Screen 1, AIBriefing.
 *
 * Prose, not a widget wall: 3-6 plain sentences in the Loan Factory voice —
 * clear, practical, human, confident without promises. Every sentence is
 * derived from the real queue, so it can never claim something that isn't true.
 *
 * Phase 1 runs AI in mock mode (AI_MODE=mock): the briefing is composed
 * deterministically from the same data the queue uses, not generated by a
 * model. That keeps it honest and free, and the model gateway slots in behind
 * this same function later.
 *
 * It never states a rate, never promises an outcome, and follows the do-not-say
 * rules in Mortgage_Compliance.
 */
import type { QueueItem } from "@/lib/queue-types";
import { moneyCompact } from "@/lib/format";

export type BriefingAction = {
  /** A short, punchy label for the chip: "The Thanh lock", "Call Chidi". */
  label: string;
  href: string;
  /** The verb on the button: "Open the file", "Call now", "Approve & send". */
  actionLabel: string;
  urgency: QueueItem["urgency"];
};

export type Briefing = {
  greeting: string;
  /** The one-line read of the day — rendered as the lead, not a bullet. */
  lead: string;
  /** The concise priority bullets (everything after the lead). */
  bullets: string[];
  /** The three highest-ranked things to actually do, as real actions. */
  topActions: BriefingAction[];
  /** Retained for callers/tests that read the flat sentence form. */
  sentences: string[];
  focus: string | null;
};

export function buildBriefing(
  firstName: string,
  items: QueueItem[],
  stats: { activeCount: number; fundedMtdVolume: number; closingNext7: number },
  now = new Date(),
): Briefing {
  const dateLine = new Intl.DateTimeFormat("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  }).format(now);

  const deadlines = items.filter((i) => i.cls === "deadline");
  const locks = deadlines.filter((i) => i.id.startsWith("lock-"));
  const closings = deadlines.filter((i) => i.id.startsWith("closing-"));
  const newLeads = items.filter((i) => i.cls === "new_lead");
  const approvals = items.filter((i) => i.cls === "ai_approval");
  const overdue = items.filter((i) => i.cls === "overdue_task");
  const appts = items.filter((i) => i.cls === "appointment");
  const stalled = items.filter((i) => i.cls === "stalled");

  const sentences: string[] = [];

  // 1. A one-line read of the day — leads first, mirroring the assistant's
  //    priority order (new leads, then follow-ups, then deadline work).
  const dayRead: string[] = [];
  if (newLeads.length) {
    dayRead.push(`${newLeads.length} new lead${newLeads.length === 1 ? "" : "s"} to call`);
  }
  if (closings.length) {
    dayRead.push(`${closings.length} closing${closings.length === 1 ? "" : "s"} this week`);
  }
  if (locks.length) {
    dayRead.push(`${locks.length} lock${locks.length === 1 ? "" : "s"} that need${locks.length === 1 ? "s" : ""} attention`);
  }
  sentences.push(
    dayRead.length
      ? `${dateLine}. ${capitalise(dayRead.join(" and "))}.`
      : `${dateLine}. Nothing is at a deadline today.`,
  );

  // 2. New leads come first — speed-to-lead is what wins deals.
  if (newLeads.length) {
    const oldest = newLeads[0];
    sentences.push(
      newLeads.length === 1
        ? `One new lead is waiting on a first call: ${oldest.personName}. Call them first.`
        : `${newLeads.length} new leads are waiting on a first call — the oldest is ${oldest.personName}. Start there.`,
    );
  }

  // 3. What's slipping — follow-ups owed and files gone quiet.
  const slipping: string[] = [];
  if (overdue.length) slipping.push(`${overdue.length} overdue follow-up${overdue.length === 1 ? "" : "s"}`);
  if (stalled.length) slipping.push(`${stalled.length} file${stalled.length === 1 ? "" : "s"} that ${stalled.length === 1 ? "has" : "have"} gone quiet`);
  if (slipping.length) sentences.push(`You also have ${slipping.join(" and ")}.`);

  // 4. Deadline risk — locks, then closings.
  for (const lock of locks.slice(0, 2)) {
    sentences.push(`${lock.headline}. ${lock.detail ?? ""}`.trim());
  }
  if (closings.length) {
    const names = closings.slice(0, 2).map((c) => c.personName).filter(Boolean);
    sentences.push(
      closings.length === 1
        ? `${closings[0].headline}.`
        : `Closings coming up for ${names.join(" and ")}.`,
    );
  }

  // 5. Approvals waiting.
  if (approvals.length) {
    sentences.push(
      `AI has ${approvals.length} thing${approvals.length === 1 ? "" : "s"} ready for your approval. Nothing goes out until you say so.`,
    );
  }

  if (appts.length) {
    sentences.push(
      appts.length === 1
        ? `One thing on your calendar: ${appts[0].headline.toLowerCase()}.`
        : `${appts.length} things on your calendar today.`,
    );
  }

  // 6. One suggested focus — the top three items in briefing priority order.
  const prioritized = [...items].sort(
    (a, b) =>
      briefingRank(a) - briefingRank(b) || a.hours - b.hours || b.amount - a.amount,
  );
  const top = prioritized.slice(0, 3);
  const focus =
    top.length >= 2
      ? `If you only do three things today: ${top
          .map((i) => focusPhrase(i))
          .join(", then ")}.`
      : null;

  if (!items.length) {
    sentences.length = 1;
    sentences.push(
      `You're caught up — nothing needs you right now. You have ${stats.activeCount} active file${stats.activeCount === 1 ? "" : "s"} and ${moneyCompact(stats.fundedMtdVolume)} funded this month.`,
    );
  }

  const trimmed = sentences.filter(Boolean).slice(0, 6);

  // The three highest-priority items become real, tappable actions.
  const topActions: BriefingAction[] = top.map((item) => ({
    label: capitalise(focusPhrase(item)),
    href: item.href,
    actionLabel: item.actionLabel,
    urgency: item.urgency,
  }));

  return {
    greeting: `Good morning, ${firstName}.`,
    lead: trimmed[0] ?? "",
    bullets: trimmed.slice(1),
    topActions,
    sentences: trimmed,
    focus,
  };
}

/**
 * The briefing's own priority order — new leads first, then follow-ups, then
 * files needing attention (quiet files and locks), then approvals, then
 * closings. The queue keeps its deadline-first CLASS_RANK; this ordering is
 * only for what the briefing surfaces most prominently.
 */
function briefingRank(item: QueueItem): number {
  switch (item.cls) {
    case "new_lead":
      return 1;
    case "overdue_task":
      return 2;
    case "stalled":
      return 3;
    case "deadline":
      return item.id.startsWith("lock-") ? 3 : 5;
    case "ai_approval":
      return 4;
    case "appointment":
      return 6;
    default:
      return 7;
  }
}

function focusPhrase(item: QueueItem): string {
  const name = item.personName?.split(" ")[0] ?? "it";
  switch (item.cls) {
    case "deadline":
      return item.id.startsWith("lock-") ? `the ${name} lock` : `${name}'s closing`;
    case "new_lead":
      return `call ${name}`;
    case "ai_approval":
      return `the draft for ${name}`;
    case "overdue_task":
      return `the overdue task on ${name}`;
    case "appointment":
      return `your ${name} meeting`;
    case "stalled":
      return `${name}, who's gone quiet`;
    default:
      return name;
  }
}

function capitalise(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
