/**
 * The morning briefing — Screen 1, AllyBriefing.
 *
 * Prose, not a widget wall: 3-6 plain sentences in the Loan Factory voice —
 * clear, practical, human, confident without promises. Every sentence is
 * derived from the real queue, so it can never claim something that isn't true.
 *
 * Phase 1 runs Ally in mock mode (ALLY_MODE=mock): the briefing is composed
 * deterministically from the same data the queue uses, not generated by a
 * model. That keeps it honest and free, and the model gateway slots in behind
 * this same function later.
 *
 * It never states a rate, never promises an outcome, and follows the do-not-say
 * rules in Mortgage_Compliance.
 */
import type { QueueItem } from "@/lib/queue-types";
import { moneyCompact } from "@/lib/format";

export type Briefing = {
  greeting: string;
  sentences: string[];
  focus: string | null;
};

export function buildBriefing(
  firstName: string,
  items: QueueItem[],
  stats: { activeCount: number; fundedMtdVolume: number; closingNext7: number },
  now = new Date(),
): Briefing {
  const dateLine = new Intl.DateTimeFormat("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  }).format(now);

  const deadlines = items.filter((i) => i.cls === "deadline");
  const locks = deadlines.filter((i) => i.id.startsWith("lock-"));
  const closings = deadlines.filter((i) => i.id.startsWith("closing-"));
  const newLeads = items.filter((i) => i.cls === "new_lead");
  const approvals = items.filter((i) => i.cls === "ally_approval");
  const overdue = items.filter((i) => i.cls === "overdue_task");
  const appts = items.filter((i) => i.cls === "appointment");
  const stalled = items.filter((i) => i.cls === "stalled");

  const sentences: string[] = [];

  // 1. A one-line read of the day.
  const dayRead: string[] = [];
  if (closings.length) {
    dayRead.push(`${closings.length} closing${closings.length === 1 ? "" : "s"} this week`);
  }
  if (locks.length) {
    dayRead.push(`${locks.length} lock${locks.length === 1 ? "" : "s"} that need${locks.length === 1 ? "s" : ""} attention`);
  }
  sentences.push(
    dayRead.length
      ? `${dateLine}. ${capitalise(dayRead.join(" and "))}.`
      : `${dateLine}. Nothing is at a deadline today.`,
  );

  // 2. Deadline risk comes first — it's what costs deals.
  for (const lock of locks.slice(0, 2)) {
    sentences.push(`${lock.headline}. ${lock.detail ?? ""}`.trim());
  }
  if (closings.length) {
    const names = closings.slice(0, 2).map((c) => c.personName).filter(Boolean);
    sentences.push(
      closings.length === 1
        ? `${closings[0].headline}.`
        : `Closings coming up for ${names.join(" and ")}.`,
    );
  }

  // 3. Overnight inputs.
  if (newLeads.length) {
    const oldest = newLeads[0];
    sentences.push(
      newLeads.length === 1
        ? `One new lead is waiting on a first call: ${oldest.personName}.`
        : `${newLeads.length} new leads are waiting on a first call — the oldest is ${oldest.personName}.`,
    );
  }

  // 4. Approvals waiting.
  if (approvals.length) {
    sentences.push(
      `Ally has ${approvals.length} thing${approvals.length === 1 ? "" : "s"} ready for your approval. Nothing goes out until you say so.`,
    );
  }

  // 5. What's slipping.
  const slipping: string[] = [];
  if (overdue.length) slipping.push(`${overdue.length} overdue task${overdue.length === 1 ? "" : "s"}`);
  if (stalled.length) slipping.push(`${stalled.length} file${stalled.length === 1 ? "" : "s"} that ${stalled.length === 1 ? "has" : "have"} gone quiet`);
  if (slipping.length) sentences.push(`You also have ${slipping.join(" and ")}.`);

  if (appts.length) {
    sentences.push(
      appts.length === 1
        ? `One thing on your calendar: ${appts[0].headline.toLowerCase()}.`
        : `${appts.length} things on your calendar today.`,
    );
  }

  // 6. One suggested focus — the top three items by rank.
  const top = items.slice(0, 3);
  const focus =
    top.length >= 2
      ? `If you only do three things today: ${top
          .map((i) => focusPhrase(i))
          .join(", then ")}.`
      : null;

  if (!items.length) {
    sentences.length = 1;
    sentences.push(
      `You're caught up — nothing needs you right now. You have ${stats.activeCount} active file${stats.activeCount === 1 ? "" : "s"} and ${moneyCompact(stats.fundedMtdVolume)} funded this month.`,
    );
  }

  return {
    greeting: `Good morning, ${firstName}.`,
    sentences: sentences.filter(Boolean).slice(0, 6),
    focus,
  };
}

function focusPhrase(item: QueueItem): string {
  const name = item.personName?.split(" ")[0] ?? "it";
  switch (item.cls) {
    case "deadline":
      return item.id.startsWith("lock-") ? `the ${name} lock` : `${name}'s closing`;
    case "new_lead":
      return `call ${name}`;
    case "ally_approval":
      return `the draft for ${name}`;
    case "overdue_task":
      return `the overdue task on ${name}`;
    case "appointment":
      return `your ${name} meeting`;
    case "stalled":
      return `${name}, who's gone quiet`;
    default:
      return name;
  }
}

function capitalise(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
